
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 862;
const int acc_off_y = 266;
const int acc_off_z = -386;
const float acc_scale_x = 15299.706926;
const float acc_scale_y = 17202.268907;
const float acc_scale_z = 17909.365833;

const int magn_off_x = -8;
const int magn_off_y = -135;
const int magn_off_z = -45;
const float magn_scale_x = 545.0;
const float magn_scale_y = 552.0;
const float magn_scale_z = 460.5;
